[build]
base = "frontend"
command = "npm install && npm run build"  # Simplified, runs in frontend/
publish = "frontend/dist"
functions = "../functions"  # Points to root-level functions/

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200