[build]
command = "npm install && cd frontend && npm install && npm run build"
publish = "frontend/dist"
functions = "functions"

[functions]
directory = "functions"
node_bundler = "esbuild"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
force = true

[build.environment]
NODE_VERSION = "18.17.0"