[build]
base = "."  # Build from root directory
command = "cd frontend && npm install && npm run build"
publish = "frontend/dist"
functions = "functions"


[[redirects]]
from = "/api/*"
to = "/api/:splat"
status = 200
