[build]
base = "frontend"
command = "npm install && npm run build"
publish = "dist"
functions = "../functions"  # Points to root functions folder

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
