[build]
base = "frontend"
command = "npm install && cd frontend && npm install && npm run build"
publish = "dist"
functions = "functions"  # Adjusted to root-level functions/

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200