[build]
command = "npm install && cd frontend && npm install && npm run build"
publish = "frontend/dist"
functions = "functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
force = true