[build]
base = "frontend"
command = "cd .. && npm install && cd frontend && npm install && npm run build"
publish = "dist"  # Relative to base (frontend/), not "frontend/dist"
functions = "../functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200