[build]
command = "cd frontend && npm install --include=dev && npm run build"
publish = "dist"
functions = "functions"

[functions]
directory = "functions"
node_bundler = "esbuild"
included_files = ["supabase.js"]

[functions.environment]
SUPABASE_URL = "https://hntrpejpiboxnlbzrbbc.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhudHJwZWpwaWJveG5sYnpyYmJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNDA4NTMsImV4cCI6MjA1ODgxNjg1M30.J4R67CjTWG6WaTtAtuHNTmDFKGaGWvA4R1gWRBBmMDc"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.environment]
NODE_VERSION = "18"
SUPABASE_URL = "https://hntrpejpiboxnlbzrbbc.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhudHJwZWpwaWJveG5sYnpyYmJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNDA4NTMsImV4cCI6MjA1ODgxNjg1M30.J4R67CjTWG6WaTtAtuHNTmDFKGaGWvA4R1gWRBBmMDc"