[build]
command = "cd frontend && npm run build"
publish = "frontend/dist"
functions = "functions"

[functions]
directory = "functions"
node_bundler = "esbuild"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.environment]
NODE_VERSION = "18"