[build]
base = "frontend"       # Set working directory to frontend/
command = "npm install && npm run build" # Install dependencies and build
publish = "dist"        # Built files in frontend/dist/
functions = "../functions" # Points to root functions/ folder

[[redirects]]
from = "/api/*"
to = "/api/:splat"
status = 200
